"""
test_coverage_gaps.py
=====================

Tests for functions and code paths that had no prior test coverage.
Generated by tick-5 coverage analysis (2026-03-31).

Covers:
- config.py: SkillChainConfig.load, save, save_keystore, load_keystore, load_trust_cache, save_trust_cache, to_dict
- hooks.py: generate_hooks_config, install_hooks, uninstall_hooks, get_installed_hooks
- ipfs_client.py: IPFSClient._validate_cid, verify_content_hash, upload_file error path
- chain_client.py: ChainClient.make_hash, _to_bytes32, LICENSE_TYPES
- contracts/addresses.py: get_addresses
- skill_packer.py: validate_manifest domain validation, SkillManifest.from_dict unknown fields
- skill_state.py: SkillStateStore._sanitize_name edge cases
- shadow_runner.py: ShadowResult.match_rate, _execute_skill fallback path
- skill_chain.py: SkillChain._merge_outputs, from_dict missing fields
- mcp_bridge/claude_settings.py: install_mcp_server, uninstall_mcp_server, is_installed
"""

from __future__ import annotations

import hashlib
import json
import os
import tempfile
from pathlib import Path
from unittest.mock import patch

import pytest


# ═══════════════════════════════════════════════════════════════════
# 1. config.py — SkillChainConfig
# ═══════════════════════════════════════════════════════════════════

class TestSkillChainConfig:
    """Tests for SkillChainConfig load/save/keystore/trust_cache."""

    def test_load_defaults_to_sepolia(self):
        from skillchain.sdk.config import SkillChainConfig, NETWORK_PRESETS
        cfg = SkillChainConfig.load(network="sepolia")
        assert cfg.network == "sepolia"
        # rpc_url may be overridden by ~/.skillchain/config.json on disk;
        # verify the network was resolved correctly
        assert cfg.chain_id in ("84532", NETWORK_PRESETS["sepolia"]["chain_id"], "")

    def test_load_mainnet(self):
        from skillchain.sdk.config import SkillChainConfig
        cfg = SkillChainConfig.load(network="mainnet")
        assert cfg.network == "mainnet"

    def test_load_env_var_override(self):
        from skillchain.sdk.config import SkillChainConfig
        with patch.dict(os.environ, {"SKILLCHAIN_RPC_URL": "http://custom-rpc"}):
            cfg = SkillChainConfig.load(network="sepolia")
            assert cfg.rpc_url == "http://custom-rpc"

    def test_save_and_reload(self, tmp_path):
        from skillchain.sdk.config import SkillChainConfig
        cfg = SkillChainConfig()
        cfg.network = "sepolia"
        cfg.node_id = "test-node-123"
        cfg.agent_platform = "claude"
        cfg.domain_tags = ["reasoning", "code"]
        # Override paths to tmp
        cfg.config_dir = tmp_path
        cfg.config_file = tmp_path / "config.json"
        cfg.keystore_file = tmp_path / "keystore.json"
        cfg.trust_cache_file = tmp_path / "trust_cache.json"
        cfg.skills_dir = tmp_path / "skills"
        cfg.validations_dir = tmp_path / "validations"
        cfg.save()
        assert cfg.config_file.exists()
        data = json.loads(cfg.config_file.read_text(encoding="utf-8"))
        assert data["node_id"] == "test-node-123"
        assert data["domain_tags"] == ["reasoning", "code"]
        # Private key must NOT be in saved config
        assert "private_key" not in data

    def test_save_keystore_and_load(self, tmp_path):
        from skillchain.sdk.config import SkillChainConfig
        cfg = SkillChainConfig()
        cfg.config_dir = tmp_path
        cfg.keystore_file = tmp_path / "keystore.json"
        ks = {"node_id": "ks-node", "wallet_address": "0xabc"}
        cfg.save_keystore(ks)
        assert cfg.keystore_file.exists()
        loaded = cfg.load_keystore()
        assert loaded["node_id"] == "ks-node"

    def test_load_keystore_missing_raises(self, tmp_path):
        from skillchain.sdk.config import SkillChainConfig
        from skillchain.sdk.exceptions import IdentityError
        cfg = SkillChainConfig()
        cfg.keystore_file = tmp_path / "nonexistent.json"
        with pytest.raises(IdentityError):
            cfg.load_keystore()

    def test_trust_cache_roundtrip(self, tmp_path):
        from skillchain.sdk.config import SkillChainConfig
        cfg = SkillChainConfig()
        cfg.trust_cache_file = tmp_path / "trust_cache.json"
        cache = {"peer-1": 0.85, "peer-2": 0.42}
        cfg.save_trust_cache(cache)
        loaded = cfg.load_trust_cache()
        assert loaded["peer-1"] == 0.85
        assert loaded["peer-2"] == 0.42

    def test_trust_cache_missing_returns_empty(self, tmp_path):
        from skillchain.sdk.config import SkillChainConfig
        cfg = SkillChainConfig()
        cfg.trust_cache_file = tmp_path / "nope.json"
        assert cfg.load_trust_cache() == {}

    def test_to_dict_excludes_private_key(self):
        from skillchain.sdk.config import SkillChainConfig
        cfg = SkillChainConfig()
        cfg.private_key = "secret"
        d = cfg.to_dict()
        assert "private_key" not in d
        assert "network" in d
        assert "node_id" in d


# ═══════════════════════════════════════════════════════════════════
# 2. hooks.py — generate, install, uninstall, list
# ═══════════════════════════════════════════════════════════════════

class TestHooks:
    """Tests for hooks.py which had ZERO test coverage."""

    def test_generate_hooks_config_has_keys(self):
        from skillchain.sdk.hooks import generate_hooks_config
        config = generate_hooks_config()
        assert "skillchain-auto-pack" in config
        assert "skillchain-post-validate" in config
        assert config["skillchain-auto-pack"]["type"] == "afterFileWrite"
        assert config["skillchain-auto-pack"]["enabled"] is True

    def test_install_hooks_creates_settings(self, tmp_path):
        from skillchain.sdk.hooks import install_hooks, _find_settings_path
        settings_file = tmp_path / "settings.json"
        with patch("skillchain.sdk.hooks._find_settings_path", return_value=settings_file):
            result = install_hooks()
        assert result is True
        assert settings_file.exists()
        data = json.loads(settings_file.read_text(encoding="utf-8"))
        assert "skillchain-auto-pack" in data["hooks"]
        assert "skillchain-post-validate" in data["hooks"]

    def test_install_hooks_preserves_existing(self, tmp_path):
        from skillchain.sdk.hooks import install_hooks
        settings_file = tmp_path / "settings.json"
        settings_file.write_text(json.dumps({"existing": True, "hooks": {"my-hook": {}}}, indent=2))
        with patch("skillchain.sdk.hooks._find_settings_path", return_value=settings_file):
            install_hooks()
        data = json.loads(settings_file.read_text(encoding="utf-8"))
        assert data["existing"] is True
        assert "my-hook" in data["hooks"]
        assert "skillchain-auto-pack" in data["hooks"]

    def test_uninstall_hooks_removes_skillchain_keys(self, tmp_path):
        from skillchain.sdk.hooks import install_hooks, uninstall_hooks
        settings_file = tmp_path / "settings.json"
        settings_file.write_text(json.dumps({
            "hooks": {"skillchain-auto-pack": {}, "skillchain-post-validate": {}, "other-hook": {}}
        }))
        with patch("skillchain.sdk.hooks._find_settings_path", return_value=settings_file):
            result = uninstall_hooks()
        assert result is True
        data = json.loads(settings_file.read_text(encoding="utf-8"))
        assert "skillchain-auto-pack" not in data["hooks"]
        assert "other-hook" in data["hooks"]

    def test_uninstall_hooks_no_file_returns_true(self, tmp_path):
        from skillchain.sdk.hooks import uninstall_hooks
        with patch("skillchain.sdk.hooks._find_settings_path", return_value=tmp_path / "nope.json"):
            assert uninstall_hooks() is True

    def test_get_installed_hooks_empty(self, tmp_path):
        from skillchain.sdk.hooks import get_installed_hooks
        with patch("skillchain.sdk.hooks._find_settings_path", return_value=tmp_path / "nope.json"):
            assert get_installed_hooks() == []

    def test_get_installed_hooks_returns_names(self, tmp_path):
        from skillchain.sdk.hooks import get_installed_hooks
        settings_file = tmp_path / "settings.json"
        settings_file.write_text(json.dumps({
            "hooks": {"skillchain-auto-pack": {}, "skillchain-post-validate": {}, "other": {}}
        }))
        with patch("skillchain.sdk.hooks._find_settings_path", return_value=settings_file):
            names = get_installed_hooks()
        assert "skillchain-auto-pack" in names
        assert "skillchain-post-validate" in names
        assert "other" not in names


# ═══════════════════════════════════════════════════════════════════
# 3. ipfs_client.py — CID validation, content hash verification
# ═══════════════════════════════════════════════════════════════════

class TestIPFSClient:
    """Tests for untested IPFSClient methods."""

    def test_validate_cid_valid(self):
        from skillchain.sdk.ipfs_client import IPFSClient
        # Should not raise
        IPFSClient._validate_cid("QmYwAPJzv5CZsnA625s3Xf2nemtYgPpHdWEz79ojWnPbdG")
        IPFSClient._validate_cid("bafybeigdyrzt5sfp7udm7hu76uh7y26nf3efuylqabf3oclgtqy55fbzdi")

    def test_validate_cid_empty_raises(self):
        from skillchain.sdk.ipfs_client import IPFSClient
        from skillchain.sdk.exceptions import IPFSError
        with pytest.raises(IPFSError, match="Empty"):
            IPFSClient._validate_cid("")

    def test_validate_cid_with_slashes_raises(self):
        from skillchain.sdk.ipfs_client import IPFSClient
        from skillchain.sdk.exceptions import IPFSError
        with pytest.raises(IPFSError, match="Invalid characters"):
            IPFSClient._validate_cid("Qm/../etc/passwd")

    def test_validate_cid_with_dotdot_raises(self):
        from skillchain.sdk.ipfs_client import IPFSClient
        from skillchain.sdk.exceptions import IPFSError
        with pytest.raises(IPFSError, match="Suspicious"):
            IPFSClient._validate_cid("Qm..abcdef")

    def test_validate_cid_too_long_raises(self):
        from skillchain.sdk.ipfs_client import IPFSClient
        from skillchain.sdk.exceptions import IPFSError
        with pytest.raises(IPFSError, match="too long"):
            IPFSClient._validate_cid("a" * 200)

    def test_verify_content_hash_correct(self):
        from skillchain.sdk.ipfs_client import IPFSClient
        data = b"hello world"
        h = hashlib.sha256(data).hexdigest()
        assert IPFSClient.verify_content_hash(data, h) is True

    def test_verify_content_hash_wrong(self):
        from skillchain.sdk.ipfs_client import IPFSClient
        assert IPFSClient.verify_content_hash(b"hello", "0000") is False

    def test_upload_file_missing_raises(self, tmp_path):
        from skillchain.sdk.ipfs_client import IPFSClient
        from skillchain.sdk.exceptions import IPFSError
        client = IPFSClient()
        with pytest.raises(IPFSError, match="not found"):
            client.upload_file(tmp_path / "nonexistent.md")

    def test_upload_directory_not_dir_raises(self, tmp_path):
        from skillchain.sdk.ipfs_client import IPFSClient
        from skillchain.sdk.exceptions import IPFSError
        f = tmp_path / "file.txt"
        f.write_text("x")
        client = IPFSClient()
        with pytest.raises(IPFSError, match="Not a directory"):
            client.upload_directory(f)

    def test_upload_directory_empty_raises(self, tmp_path):
        from skillchain.sdk.ipfs_client import IPFSClient
        from skillchain.sdk.exceptions import IPFSError
        empty = tmp_path / "empty"
        empty.mkdir()
        client = IPFSClient(provider="pinata", api_key="k", secret_key="s")
        with pytest.raises(IPFSError, match="Empty directory"):
            client.upload_directory(empty)


# ═══════════════════════════════════════════════════════════════════
# 4. chain_client.py — utility methods (no web3 needed)
# ═══════════════════════════════════════════════════════════════════

class TestChainClientUtils:
    """Tests for ChainClient utility methods that don't need web3."""

    def test_make_hash_returns_32_bytes(self):
        from skillchain.sdk.chain_client import ChainClient
        client = ChainClient.__new__(ChainClient)
        h = client.make_hash("test-data")
        assert isinstance(h, bytes)
        assert len(h) == 32

    def test_make_hash_deterministic(self):
        from skillchain.sdk.chain_client import ChainClient
        client = ChainClient.__new__(ChainClient)
        assert client.make_hash("foo") == client.make_hash("foo")
        assert client.make_hash("foo") != client.make_hash("bar")

    def test_to_bytes32(self):
        from skillchain.sdk.chain_client import ChainClient
        client = ChainClient.__new__(ChainClient)
        result = client._to_bytes32("node-123")
        assert isinstance(result, bytes)
        assert len(result) == 32

    def test_license_types_mapping(self):
        from skillchain.sdk.chain_client import LICENSE_TYPES
        assert LICENSE_TYPES["MIT"] == 0
        assert LICENSE_TYPES["APACHE2"] == 1
        assert LICENSE_TYPES["GPL3"] == 2
        assert LICENSE_TYPES["PROPRIETARY"] == 3

    def test_transaction_result_dataclass(self):
        from skillchain.sdk.chain_client import TransactionResult
        tr = TransactionResult(tx_hash="0xabc", block_number=100, gas_used=21000, status=1)
        assert tr.status == 1
        assert tr.gas_used == 21000


# ═══════════════════════════════════════════════════════════════════
# 5. contracts/addresses.py — get_addresses
# ═══════════════════════════════════════════════════════════════════

class TestContractAddresses:
    """Tests for get_addresses which had no coverage."""

    def test_get_addresses_sepolia(self):
        from skillchain.sdk.contracts.addresses import get_addresses
        addrs = get_addresses("sepolia")
        assert "skill_token" in addrs
        assert "node_registry" in addrs
        assert "marketplace" in addrs

    def test_get_addresses_localhost(self):
        from skillchain.sdk.contracts.addresses import get_addresses
        addrs = get_addresses("localhost")
        assert addrs["skill_token"] == "0x5FbDB2315678afecb367f032d93F642f64180aa3"

    def test_get_addresses_unknown_falls_back(self):
        from skillchain.sdk.contracts.addresses import get_addresses
        addrs = get_addresses("fantasy-network")
        # Should fall back to base_sepolia
        assert "skill_token" in addrs

    def test_all_networks_have_same_keys(self):
        from skillchain.sdk.contracts.addresses import CONTRACT_ADDRESSES
        keys = None
        for network, addrs in CONTRACT_ADDRESSES.items():
            if keys is None:
                keys = set(addrs.keys())
            else:
                assert set(addrs.keys()) == keys, f"Network {network} has different keys"


# ═══════════════════════════════════════════════════════════════════
# 6. skill_packer.py — additional validation edge cases
# ═══════════════════════════════════════════════════════════════════

class TestSkillPackerEdgeCases:
    """Edge cases not covered in existing tests."""

    def test_validate_manifest_invalid_domain(self):
        from skillchain.sdk.skill_packer import validate_manifest
        errors = validate_manifest({
            "name": "test",
            "version": "1.0.0",
            "domain": "invalid domain!",
            "description": "test",
        })
        assert any("Invalid domain" in e for e in errors)

    def test_validate_manifest_invalid_price_type(self):
        from skillchain.sdk.skill_packer import validate_manifest
        errors = validate_manifest({
            "name": "test",
            "version": "1.0.0",
            "domain": "code",
            "description": "test",
            "price": "not-a-number",
        })
        assert any("Invalid price" in e for e in errors)

    def test_validate_manifest_invalid_graduation_threshold_type(self):
        from skillchain.sdk.skill_packer import validate_manifest
        errors = validate_manifest({
            "name": "test",
            "version": "1.0.0",
            "domain": "code",
            "description": "test",
            "graduation_threshold": "not-a-float",
        })
        assert any("Invalid graduation_threshold" in e for e in errors)

    def test_skill_manifest_from_dict_ignores_unknown_fields(self):
        from skillchain.sdk.skill_packer import SkillManifest
        m = SkillManifest.from_dict({
            "name": "test",
            "version": "1.0.0",
            "domain": "code",
            "description": "desc",
            "unknown_field": "should be ignored",
            "another_unknown": 42,
        })
        assert m.name == "test"
        assert not hasattr(m, "unknown_field")

    def test_sign_provenance_anonymous(self):
        from skillchain.sdk.skill_packer import sign_provenance, SkillManifest
        manifest = SkillManifest(name="test", version="1.0.0", domain="code", description="desc")
        prov = sign_provenance({}, manifest, "abc123hash")
        assert prov["author_node_id"] == "anonymous"
        assert prov["author_wallet"] == ""
        assert prov["chain_hash"]  # non-empty


# ═══════════════════════════════════════════════════════════════════
# 7. skill_state.py — sanitize_name edge cases
# ═══════════════════════════════════════════════════════════════════

class TestSkillStateSanitize:
    """Edge cases for SkillStateStore._sanitize_name."""

    def test_sanitize_removes_slashes(self):
        from skillchain.sdk.skill_state import SkillStateStore
        assert "/" not in SkillStateStore._sanitize_name("a/b/c")
        assert "\\" not in SkillStateStore._sanitize_name("a\\b\\c")

    def test_sanitize_removes_dotdot(self):
        from skillchain.sdk.skill_state import SkillStateStore
        result = SkillStateStore._sanitize_name("../../etc/passwd")
        assert ".." not in result

    def test_sanitize_removes_null_bytes(self):
        from skillchain.sdk.skill_state import SkillStateStore
        result = SkillStateStore._sanitize_name("skill\0name")
        assert "\0" not in result

    def test_sanitize_empty_returns_unnamed(self):
        from skillchain.sdk.skill_state import SkillStateStore
        assert SkillStateStore._sanitize_name("") == "_unnamed"

    def test_sanitize_only_dots_returns_unnamed(self):
        from skillchain.sdk.skill_state import SkillStateStore
        assert SkillStateStore._sanitize_name("...") == "_unnamed"


# ═══════════════════════════════════════════════════════════════════
# 8. shadow_runner.py — ShadowResult properties, fallback execution
# ═══════════════════════════════════════════════════════════════════

class TestShadowRunnerAdditional:
    """Additional coverage for ShadowRunner/ShadowResult."""

    def test_match_rate_zero_when_empty(self):
        from skillchain.sdk.shadow_runner import ShadowResult
        r = ShadowResult(passed=False, match_count=0, shadow_count=0)
        assert r.match_rate == 0.0

    def test_match_rate_computed(self):
        from skillchain.sdk.shadow_runner import ShadowResult
        r = ShadowResult(passed=True, match_count=3, shadow_count=4)
        assert r.match_rate == 0.75

    def test_execute_skill_no_steps_returns_full_content(self):
        from skillchain.sdk.shadow_runner import ShadowRunner
        runner = ShadowRunner()
        # Content with no numbered steps, bullets, or directives
        content = "This is just a plain description.\nNo special formatting here."
        result = runner._execute_skill(content, "test input")
        # Should return the full content since no steps were found
        assert result == content.strip()

    def test_execute_skill_with_steps_extracts_them(self):
        from skillchain.sdk.shadow_runner import ShadowRunner
        runner = ShadowRunner()
        content = "# My Skill\n\n1. Do first thing\n2. Do second thing\n- Also do this\n"
        result = runner._execute_skill(content, "input data")
        assert "Applied 3 steps" in result
        assert "Step 1:" in result
        assert "Step 2:" in result
        assert "Step 3:" in result
        assert "Input context: input data" in result

    def test_validate_timeout_error_handled(self):
        from skillchain.sdk.shadow_runner import ShadowRunner
        runner = ShadowRunner(shadow_count=1)

        def _fake_execute(self_inner, content, inp):
            raise TimeoutError("timed out")

        with patch.object(ShadowRunner, "_execute_skill", _fake_execute):
            result = runner.validate("# skill content", [{"input": "x", "expected_output": "y"}])
        assert result.shadow_count == 1
        assert result.match_count == 0
        assert result.similarity_scores == [0.0]
        assert "Timeout" in result.errors[0]

    def test_validate_generic_error_handled(self):
        from skillchain.sdk.shadow_runner import ShadowRunner
        runner = ShadowRunner(shadow_count=1)

        def _fake_execute(self_inner, content, inp):
            raise RuntimeError("something broke")

        with patch.object(ShadowRunner, "_execute_skill", _fake_execute):
            result = runner.validate("# skill content", [{"input": "x", "expected_output": "y"}])
        assert result.shadow_count == 1
        assert result.match_count == 0
        assert "something broke" in result.errors[0]


# ═══════════════════════════════════════════════════════════════════
# 9. skill_chain.py — _merge_outputs, from_dict edge cases
# ═══════════════════════════════════════════════════════════════════

class TestSkillChainAdditional:
    """Additional coverage for SkillChain internals."""

    def test_merge_outputs_empty(self):
        from skillchain.sdk.skill_chain import SkillChain
        result = SkillChain._merge_outputs({})
        assert result == {}

    def test_merge_outputs_preserves_alias_keys(self):
        from skillchain.sdk.skill_chain import SkillChain
        outputs = {
            "step1": {"key1": "val1"},
            "step2": {"key2": "val2"},
        }
        merged = SkillChain._merge_outputs(outputs)
        assert merged["key1"] == "val1"
        assert merged["key2"] == "val2"
        assert merged["step1"] == {"key1": "val1"}
        assert merged["step2"] == {"key2": "val2"}

    def test_merge_outputs_later_overwrites_earlier(self):
        from skillchain.sdk.skill_chain import SkillChain
        outputs = {
            "step1": {"shared_key": "first"},
            "step2": {"shared_key": "second"},
        }
        merged = SkillChain._merge_outputs(outputs)
        assert merged["shared_key"] == "second"

    def test_from_dict_missing_fields_graceful(self):
        from skillchain.sdk.skill_chain import SkillChain
        chain = SkillChain.from_dict({})
        assert chain.name == "unnamed"
        assert chain.description == ""

    def test_from_dict_steps_without_optional_fields(self):
        from skillchain.sdk.skill_chain import SkillChain
        chain = SkillChain.from_dict({
            "name": "test",
            "steps": [{"skill_name": "s1"}],
        })
        assert len(chain._steps) == 1
        assert chain._steps[0].skill_name == "s1"
        assert chain._steps[0].depends_on == []

    def test_visualize_disconnected_nodes(self):
        from skillchain.sdk.skill_chain import SkillChain
        chain = SkillChain("test")
        chain.add("s1", alias="a")
        chain.add("s2", alias="b")  # No dependency = both are roots
        viz = chain.visualize()
        assert "a (s1)" in viz
        assert "b (s2)" in viz


# ═══════════════════════════════════════════════════════════════════
# 10. mcp_bridge/claude_settings.py — install/uninstall/is_installed
# ═══════════════════════════════════════════════════════════════════

class TestClaudeSettings:
    """Tests for mcp_bridge/claude_settings.py — zero prior coverage."""

    def test_install_mcp_server(self, tmp_path):
        from skillchain.sdk.mcp_bridge import claude_settings
        settings_file = tmp_path / "settings.json"
        with patch.object(claude_settings, "_SETTINGS_PATH", settings_file):
            result = claude_settings.install_mcp_server()
        assert result == settings_file
        data = json.loads(settings_file.read_text(encoding="utf-8"))
        assert "skillchain" in data["mcpServers"]
        assert data["mcpServers"]["skillchain"]["command"] == "skillchain"

    def test_install_mcp_server_preserves_existing(self, tmp_path):
        from skillchain.sdk.mcp_bridge import claude_settings
        settings_file = tmp_path / "settings.json"
        settings_file.write_text(json.dumps({"mcpServers": {"other": {}}, "foo": "bar"}))
        with patch.object(claude_settings, "_SETTINGS_PATH", settings_file):
            claude_settings.install_mcp_server()
        data = json.loads(settings_file.read_text(encoding="utf-8"))
        assert "other" in data["mcpServers"]
        assert "skillchain" in data["mcpServers"]
        assert data["foo"] == "bar"

    def test_uninstall_mcp_server(self, tmp_path):
        from skillchain.sdk.mcp_bridge import claude_settings
        settings_file = tmp_path / "settings.json"
        settings_file.write_text(json.dumps({"mcpServers": {"skillchain": {}, "other": {}}}))
        with patch.object(claude_settings, "_SETTINGS_PATH", settings_file):
            result = claude_settings.uninstall_mcp_server()
        assert result is True
        data = json.loads(settings_file.read_text(encoding="utf-8"))
        assert "skillchain" not in data.get("mcpServers", {})
        assert "other" in data.get("mcpServers", {})

    def test_uninstall_not_present_returns_false(self, tmp_path):
        from skillchain.sdk.mcp_bridge import claude_settings
        settings_file = tmp_path / "settings.json"
        settings_file.write_text(json.dumps({"mcpServers": {"other": {}}}))
        with patch.object(claude_settings, "_SETTINGS_PATH", settings_file):
            assert claude_settings.uninstall_mcp_server() is False

    def test_is_installed_true(self, tmp_path):
        from skillchain.sdk.mcp_bridge import claude_settings
        settings_file = tmp_path / "settings.json"
        settings_file.write_text(json.dumps({"mcpServers": {"skillchain": {}}}))
        with patch.object(claude_settings, "_SETTINGS_PATH", settings_file):
            assert claude_settings.is_installed() is True

    def test_is_installed_false(self, tmp_path):
        from skillchain.sdk.mcp_bridge import claude_settings
        settings_file = tmp_path / "settings.json"
        settings_file.write_text(json.dumps({"mcpServers": {}}))
        with patch.object(claude_settings, "_SETTINGS_PATH", settings_file):
            assert claude_settings.is_installed() is False

    def test_is_installed_no_file(self, tmp_path):
        from skillchain.sdk.mcp_bridge import claude_settings
        with patch.object(claude_settings, "_SETTINGS_PATH", tmp_path / "nope.json"):
            assert claude_settings.is_installed() is False


# ═══════════════════════════════════════════════════════════════════
# 11. agent_social.py — _sanitize_id edge cases
# ═══════════════════════════════════════════════════════════════════

class TestAgentSocialSanitize:
    """Edge cases for _sanitize_id helper."""

    def test_sanitize_id_removes_slashes(self):
        from skillchain.sdk.agent_social import _sanitize_id
        assert "/" not in _sanitize_id("a/b/c")
        assert "\\" not in _sanitize_id("a\\b")

    def test_sanitize_id_removes_dotdot(self):
        from skillchain.sdk.agent_social import _sanitize_id
        result = _sanitize_id("../../../etc")
        assert ".." not in result

    def test_sanitize_id_empty_returns_invalid(self):
        from skillchain.sdk.agent_social import _sanitize_id
        assert _sanitize_id("") == "_invalid"

    def test_sanitize_id_null_bytes(self):
        from skillchain.sdk.agent_social import _sanitize_id
        result = _sanitize_id("id\0with\0nulls")
        assert "\0" not in result


# ═══════════════════════════════════════════════════════════════════
# 12. exceptions.py — hierarchy checks
# ═══════════════════════════════════════════════════════════════════

class TestExceptionHierarchy:
    """Verify all exceptions inherit from SkillChainError."""

    def test_all_exceptions_inherit_base(self):
        from skillchain.sdk.exceptions import (
            SkillChainError, ValidationError, ChainError,
            IPFSError, IdentityError, PackingError,
        )
        for exc_class in (ValidationError, ChainError, IPFSError, IdentityError, PackingError):
            assert issubclass(exc_class, SkillChainError)

    def test_catch_base_catches_all(self):
        from skillchain.sdk.exceptions import SkillChainError, ChainError
        with pytest.raises(SkillChainError):
            raise ChainError("test")
